export const tomorrow = {
  url: 'https://api.tomorrow.io/v4/timelines',
  fields: [
    'temperatureMin',
    'temperatureMax',
    'temperatureAvg',
    'temperatureMinTime',
    'temperatureMaxTime',
    'temperatureApparent',
    'dewPoint',
    'humidity',
    'windSpeed',
    'windGust',
    'windDirection',
    'pressureSurfaceLevel',
    'pressureSeaLevel',
    'precipitationIntensity',
    'precipitationType',
    'precipitationProbability',
    'sunriseTime',
    'sunsetTime',
    'visibility',
    'cloudCover',
    'cloudBase',
    'cloudCeiling',
    'moonPhase',
    'uvIndex',
    'weatherCodeFullDay',
    'weatherCodeDay',
    'weatherCodeNight',
    'weatherCode',
  ],
  units: 'imperial',
  timesteps: ['current', '1m', '5m', '15m', '30m', '1h', '1d'],
};
