export interface Value {
  temperatureMin: number,
  temperatureMax: number,
  temperatureAvg: number,
  temperatureApparent: number,
  temperatureMinTime: string,
  temperatureMaxTime: string,
  dewPoint: number,
  humidity: number,
  windSpeed: number,
  windGust: number,
  windDirection: number,
  pressureSurfaceLevel: number,
  pressureSeaLevel: number,
  precipitationIntensity: number,
  precipitationType: number,
  precipitationProbability: number,
  sunriseTime: string,
  sunsetTime: string,
  visibility: number,
  cloudCover: number,
  cloudBase: number,
  cloudCeiling: number,
  moonPhase: number,
  uvIndex: number,
  weatherCodeFullDay: number,
  weatherCodeDay: number,
  weatherCodeNight: number,
  weatherCode: number,
}

export interface Data {
  timestep: 'current' | '1m' | '5m' | '15m' | '30m' | '1h' | '1d',
  startTime: string,
  endTime: string,
  intervals: [{ startTime: string, values: Value }],
}
